Repository nvbach91/4IZ268-2024-2025-ZS, pull requests merged in 2025-01, with the labels that each got.

#201 monj06-sp2
  www/monj06/sp2/css/styles.css
  www/monj06/sp2/images/btn_strava_connectwith_orange.png
  www/monj06/sp2/index.html
  www/monj06/sp2/js/main.js
Labels: invalid, pending

#238 plul01-sp2
  www/plul01/sp2/index.html
  www/plul01/sp2/js/main.js
  www/plul01/sp2/style/style.css
Labels: late PR

#237 jalm00-sp2
  www/jalm00/sp2/README.md
  www/jalm00/sp2/eslint.config.js
  www/jalm00/sp2/index.html
  www/jalm00/sp2/package-lock.json
  www/jalm00/sp2/package.json
  www/jalm00/sp2/postcss.config.js
  www/jalm00/sp2/sp2/assets/index-DRvM6ZAO.js
  www/jalm00/sp2/sp2/assets/index-xeFZdLPi.css
  www/jalm00/sp2/sp2/index.html
  www/jalm00/sp2/src/App.jsx
  www/jalm00/sp2/src/index.css
  www/jalm00/sp2/src/main.jsx
  www/jalm00/sp2/src/pages/Drink.jsx
  www/jalm00/sp2/src/pages/Home.jsx
  www/jalm00/sp2/tailwind.config.js
  www/jalm00/sp2/vite.config.js
Labels: late PR

#252 neme06-sp2
  www/neme06/sp2/config.env
  www/neme06/sp2/css/styles.css
  www/neme06/sp2/index.html
  www/neme06/sp2/js/app.js
Labels: late PR

#233 lech00-sp2
  www/lech00/sp2/css/main.css
  www/lech00/sp2/index.html
  www/lech00/sp2/js/main.js
Labels: late PR

#241 nguq05-sp2
  www/nguq05/sp2/css/styles.css
  www/nguq05/sp2/index.html
  www/nguq05/sp2/js/main.js
Labels: late PR

#250 semm10-sp2
  www/semm10/sp2/css/style.css
  www/semm10/sp2/index.html
  www/semm10/sp2/js/main.js
Labels: late PR

#197 pokv03-sp2
  www/pokv03/sp2/css/style.css
  www/pokv03/sp2/index.html
  www/pokv03/sp2/js/main.js
  www/pokv03/sp2/name-data.json
Labels: pending

#232 mera06-sp2
  www/mera06/sp-02/css/styles.css
  www/mera06/sp-02/docs_cz.html
  www/mera06/sp-02/docs_en.html
  www/mera06/sp-02/index.html
  www/mera06/sp-02/js/script.js
Labels: late PR

#203 maso02-sp2
  www/maso02/sp2/index.html
  www/maso02/sp2/src/auth/login/Login.jsx
  www/maso02/sp2/src/auth/signup/Signup.jsx
  www/maso02/sp2/src/components/AllTodoLists.jsx
  www/maso02/sp2/src/components/App.jsx
  www/maso02/sp2/src/components/AppHeader.jsx
  www/maso02/sp2/src/components/CurrentTodoList.jsx
  www/maso02/sp2/src/components/DeleteDialog.jsx
  www/maso02/sp2/src/components/NewListDialog.jsx
  www/maso02/sp2/src/hooks/useTodoList.js
  www/maso02/sp2/src/hooks/useTodoLists.js
  www/maso02/sp2/src/main.jsx
  www/maso02/sp2/src/providers/AppState.jsx
  www/maso02/sp2/src/utils.js
Labels: pending

#183 vava06-sp2
  www/vava06/sp2/CSS/style.css
  www/vava06/sp2/Images/favicon_school.png
  www/vava06/sp2/Images/my_profile.png
  www/vava06/sp2/JS/main.js
  www/vava06/sp2/index.html
  www/vava06/sp2/style.css
Labels: pending

#231 rezd10-sp2
  www/REZD10/sp2/css/style.css
  www/REZD10/sp2/img/favicon.ico
  www/REZD10/sp2/index.html
  www/REZD10/sp2/js/main.js
Labels: late PR
